### ISSUE TITLE
Merge ?

### ISSUE THREAD

**Issue by benben962** [theScrabi/ShareWithNewPipe#1]
The idea behind the app is great ! Why don't you merge the code with Newpipe's original ? Do you plan to do it in the future ?

**Comment by theScrabi** [comment]
No the Idea behind this app is to seperate it from newpipe. We had the problem that some wanted this feature, and some didn't want it. By offering it as a separate app, you can choose yourself if you want it or not.

**Comment by benben962** [comment]
Ok, thank you for your answer :)

**Comment by theScrabi** [comment]
No probs :)

**Comment by epitron** [comment]
I think this makes more sense integrated with NewPipe as well... It's a 1.2 megabyte app that just sends an URL to another app.

Why would people want to disable this? Do they think it clutters up their share menu?

**Comment by theScrabi** [comment]
I had this discussion over at the NewPipe issues page, where people argued about exactly this.

**Comment by epitron** [comment]
Ah, I see. (Issues 101 and 84, in case others want to follow the trail.)
